# zldface_server Global Configuration

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[ZLDFace-Server]'
  director: ${LOGGING_DIR:log}
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# redis configuration
redis:
  db: ${REDIS_DB:2}
  url: ${REDIS_CACHE:redis://127.0.0.1:6379/}

# system configuration
system:
  debug: ${DEBUG:True}
  addr: 8888

# mysql connect configuration
mysql:
  host: ${MYSQL_HOST:127.0.0.1}
  port: ${MYSQL_PORT:3306}
  user: ${MYSQL_USER:zldtest}
  password: ${MYSQL_PASSWORD:Khfdf*7123gdUIUYf}
  db: ${MYSQL_DB:zldtest}
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: false
  log-zap: "warn"

# storage configuration
storage:
  regdir: ${REGISTER_IMG_DIR:face/reg/}
  verdir: ${HPFACE_IMG_DIR:face/ver/}

# 认证方式
auth: 'ZldAuth'
