# zldface_server Global Configuration

# zap logger configuration
zap:
    level: 'info'
    format: 'console'
    prefix: '[ZLDFace-Server]'
    director: ${LOGGING_DIR:log}
    link-name: 'latest_log'
    show-line: true
    encode-level: 'LowercaseLevelEncoder'
    stacktrace-key: 'stacktrace'
    log-in-console: true

# redis configuration
redis:
    db: ${REDIS_CACHE_DBNO:2}
    url: ${REDIS_CACHE:redis://127.0.0.1:6379/}

# system configuration
system:
    debug: ${DEBUG:True}
    addr: 8888
    multipoint: true # 是否多节点部署
    multipartmemory: ${MULTIPART_MEMORY:10485760}
    matchconcurrency: ${MATCH_CONCURRENCY:20}


# mysql connect configuration
mysql:
    host: ${MYSQL_HOST:127.0.0.1}
    port: ${MYSQL_PORT:3306}
    user: ${MYSQL_USER:zldtest}
    password: ${MYSQL_PASSWORD:Khfdf*7123gdUIUYf}
    db: ${MYSQL_DB:zldtest}
    config: 'charset=utf8mb4&parseTime=True&loc=Local'
    max-idle-conns: 10
    max-open-conns: 100
    log-mode: false
    log-zap: "warn"
    slow-log: 200  # 慢日志200ms, DEBUG模式为1ms

# storage configuration
storage:
    regdir: ${REGISTER_IMG_DIR:face/reg/}  # 注册人脸照片路径
    verdir: ${HPFACE_IMG_DIR:face/ver/}  # 识别人脸照片路径

# 认证方式, 可自定义实现, 然后修改配置. DEBUG=True不开启认证
auth: 'OAuth2'
# oauth2.0认证方式，因为只有一个应用接入，暂时只做一个superToken
oauth2:
    superToken: ${SUPER_TOKEN:5kcUmuywagv99+asfs0f-b$#}

arcsoft:
    expiredAt: '2022-08-22' # 因免费版一年之后需要重新激活，如格式不正确则不报警
    alarmDays: 5  # 在expiredAt之前几天会预警，建议大于3天。配置0则关闭报警