// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "DengLingfei",
            "email": "denglingfei@zlddata.cn"
        },
        "license": {
            "name": "Apache2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/group/users/v1": {
            "post": {
                "description": "add users to a group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create group users",
                "parameters": [
                    {
                        "description": "分组id, 用户uid列表",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.FaceGroupUser"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "{\"msg\":\"添加成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete users from a group",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Delete group users",
                "parameters": [
                    {
                        "description": "分组id, 用户uid列表",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.FaceGroupUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"msg\":\"删除成功\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/groups/v1": {
            "post": {
                "description": "create a group using gid and name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Greate a group",
                "parameters": [
                    {
                        "description": "group id, group name",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.FaceGroup"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.FaceGroup"
                        }
                    }
                }
            }
        },
        "/user/match/v1": {
            "post": {
                "description": "post a faceFile to match a user in a group.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Match a user",
                "parameters": [
                    {
                        "type": "file",
                        "description": "faceFile",
                        "name": "faceFile",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "group id",
                        "name": "gid",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/recognition.Closest"
                        }
                    }
                }
            }
        },
        "/users/v1": {
            "post": {
                "description": "create user if uid not exists else update",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create or Update user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "uid",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "faceFile文件",
                        "name": "faceFile",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "group id",
                        "name": "gid",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "人脸特征文件, binary格式",
                        "name": "faceFeature",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "人脸照片路径（服务器已存在的相对路径）",
                        "name": "faceImagePath",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.FaceUser"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.FaceGroup": {
            "type": "object",
            "properties": {
                "gid": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.FaceUser": {
            "type": "object",
            "properties": {
                "faceFeature": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "recognition.Closest": {
            "type": "object",
            "properties": {
                "key": {
                    "description": "用户自定义的key, 可以是身份证号，可以是文件路径等",
                    "type": "string"
                },
                "score": {
                    "type": "number"
                }
            }
        },
        "request.FaceGroup": {
            "type": "object",
            "required": [
                "gid",
                "name"
            ],
            "properties": {
                "gid": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "request.FaceGroupUser": {
            "type": "object",
            "required": [
                "gid",
                "uids"
            ],
            "properties": {
                "gid": {
                    "type": "string"
                },
                "uids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8888",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Swagger Example API",
	Description: "This a face recognition server using arcsoft face engine",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
